### PR TITLE
Update to use std::filesystem rather than Boost

### LINKED ISSUE #232: An API for getting temp path in Filesystem.hh
## Desired behavior

`Filesystem.hh` should provide a function for getting a temp path suitable for the current operating system.

## Alternatives considered

N/A

## Implementation suggestion

Use the behavior as described in here:
https://www.boost.org/doc/libs/1_75_0/libs/filesystem/doc/reference.html#temp_directory_path
To cover both Linux/macOS and Windows.

## Additional context

`common::cwd()` is often used to "get a path to save a file" currently.
The problem with this approach is that CWD is not necessarily writable.
`av/src/VideoEncoder.cc` contains an example of this pattern.

### PR DESCRIPTION
**Pull request by mjcarroll**
# 🎉 Remove FilesystemBoost.cc in favor of std::filesystem

## Summary

Remove the vendored `FilesystemBoost.cc` file in favor of using `std::filesystem`.

## Test it

Functionality should remain the same across the stack, and all local unit/integration tests should pass on all platforms.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

File: include/ignition/common/TempDirectory.hh [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ *
+ */
+
+#ifndef IGNITION_COMMON_TEMPDIRECTORY_HH_
+#define IGNITION_COMMON_TEMPDIRECTORY_HH_
+
+#include <string>
```
Comment (ahcorde) [inline include/ignition/common/TempDirectory.hh:21]: alphabetize

File: include/ignition/common/TempDirectory.hh [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+    std::string IGNITION_COMMON_VISIBLE createTempDirectory(
+        const std::string &_baseName,
+        const std::string &_parentPath,
+        const FilesystemWarningOp _warningOp = FSWO_LOG_WARNINGS);
+
+    /// \class TempDirectory TempDirectory.hh ignitin/common/TempDirectory.hh
+    /// \brief Create a temporary directory in the OS temp location.
+    class TempDirectory
+    {
+      public: TempDirectory(const std::string &_prefix = "temp_dir",
```
Comment (ahcorde) [inline include/ignition/common/TempDirectory.hh:60]: document methods

File: src/DirIter.cc [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+
+DirIter::DirIter(const std::string &_in):
+  DirIter()
+{
+  try {
+    this->dataPtr->it = fs::directory_iterator(_in);
+  }
+  catch (const fs::filesystem_error &ex)
+  {
+  }
```
Comment (ahcorde) [inline src/DirIter.cc:48]: Error msgs ?

**Review by ahcorde — CHANGES_REQUESTED** [review]
I made some minor comments and I noticed that it's still a draft. 

Can you also test `ign-fuel-tools` ? just to check that we are not breaking things on Windows

File: src/DirIter.cc (hunk 3 above)
Comment (mjcarroll) [reply src/DirIter.cc:48]: This doesn't really need an error message.  If the path is invalid, then this will be set to the `::end()` iterator, so any loops will end.

**Comment by mjcarroll** [comment]
`ignition_common-ci-pr_any-homebrew-amd64` is expected to fail because `std::filesystem` isn't supported on 10.14

**Review by ahcorde — CHANGES_REQUESTED** [review]
Conflicts

**Review by ahcorde — CHANGES_REQUESTED** [review]
Mac and Windows are failing

**Comment by mjcarroll** [comment]
> Mac and Windows are failing

Windows is failing because the `ign-utils` dependency introduced in #244.

It is expected that the Jenkins macOS build will fail, as it is using 10.14.  The new GitHub actions-based macOS build is the one we should be referring to from this PR forward.

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by chapulina** [comment]
Homebrew is not happy yet:

```
/Users/jenkins/workspace/ignition_common-ci-pr_any-homebrew-amd64/ign-common/src/DirIter.cc:31:15: error: 'directory_iterator' is unavailable: introduced in macOS 10.15
  public: fs::directory_iterator it;
```

**Comment by mjcarroll** [comment]
> Homebrew is not happy yet:

Homebrew is expected to fail starting with this PR.  `std::filesystem` is not supported on macOS 10.14.  This is why I added the second actions-based CI against macOS 10.15

**Comment by chapulina** [comment]
> Homebrew is expected to fail starting with this PR.

**Comment by mjcarroll** [comment]
> So should we disable that job, or update it to use 10.15?

Probably a question best answered by @scpeters and @j-rivero .

My understanding is that 10.14 will go EOL sometime around the end of October, sometime after Monterey comes out.

At the very least, we should probably consider moving to 10.15 for all CI workers before 10.14 goes EOL.

**Comment by chapulina** [comment]
I made homebrew checks not required for stable branches, ticketed https://github.com/ignitionrobotics/ign-common/issues/249 and updated https://github.com/ignition-tooling/release-tools/issues/398

**Comment by chapulina** [comment]
Ignition officially supports gcc >= 8, but we have a project that's been using gcc 7 and skipping things like tests and some dependencies. I believe that merging this would break that use case.

We don't have an obligation to support that use case, but considering that this PR is not addressing a bug, how about retargeting to `main` so we don't break it?

**Comment by mjcarroll** [comment]
This has now been targeted to `main`/`ign-common5` and could use another review.

**Comment by nkoenig** [comment]
Should the DirIter class be marked as deprecated? There are some no-op functions, and it looks like we should directly use `std::filesystem`.

**Comment by scpeters** [comment]
I'll start a windows CI / colcon build using this branch to see how it affects downstream packages

**Comment by scpeters** [comment]
> I'll start a windows CI / colcon build using this branch to see how it affects downstream packages

but nothing depends on ignition-common5 yet, so never mind

**Comment by mjcarroll** [comment]
> I'll start a windows CI / colcon build using this branch to see how it affects downstream packages

I did run a full build on my system when it was still targeting ign-common4 with no issues. Since this is largely exactly replicating existing functionality, I don't anticipate any problems.

**Comment by mjcarroll** [comment]
> Should the DirIter class be marked as deprecated? There are some no-op functions, and it looks like we should directly use std::filesystem.

The same could be said with a few of the other functions in here.  This was originally intended to be a minimally-invasive drop in replacement for our current implementation.  

Since this is targeting `main`, we may consider doing this in two passes, the first to update everything to not use `FilesystemBoost`, and then another round for deprecations?

**Comment by mjcarroll** [comment]
This is now ready for another review.  For ease of review, it is now split into two commits:

* f10377d - This commit is purely changed to the source code, with no corresponding test changes. This should demonstrate that the changes are compatible.
* 3a3f1cb - Changes to the tests to remove functionality that is replaced by std::filesystem  (This is in pr #282 )

File: src/DirIter.cc [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+}
+
+//////////////////////////////////////////////////
+void DirIter::Next() {}
+
+//////////////////////////////////////////////////
+void DirIter::SetInternalEmpty() {}
+
+//////////////////////////////////////////////////
+void DirIter::CloseHandle() {}
```
Comment (chapulina) [inline src/DirIter.cc:80]: Do we need these empty functions? They're private, we could just remove them without breaking API

File: src/DirIter.cc [hunk 5]
```diff
@@ -0,0 +1,84 @@
...
+namespace fs = std::filesystem;
+
+namespace ignition
+{
+namespace common
+{
+
+class DirIter::Implementation
+{
+  public: fs::directory_iterator it;
```
Comment (chapulina) [inline src/DirIter.cc:31]:
```suggestion
  /// \brief Filesystem iterator that this class is wrapping
  public: fs::directory_iterator it;
```

File: src/Filesystem.cc [hunk 6]
```diff
@@ -36,466 +30,293 @@
...
 #endif
 
-namespace igncmn = ignition::common;
-using namespace ignition;
-using namespace igncmn;
-
-/////////////////////////////////////////////////
-bool ignition::common::isFile(const std::string &_path)
+// Return true if success, false if error
+inline bool fs_warn(const std::string &_fcn,
```
Comment (chapulina) [inline src/Filesystem.cc:44]:
```suggestion
inline bool fsWarn(const std::string &_fcn,
```

File: src/Filesystem.cc [hunk 7]
```diff
@@ -36,466 +30,293 @@
...
-# define IGN_PATH_MAX PATH_MAX
-#elif defined(_XOPEN_PATH_MAX)
-# define IGN_PATH_MAX _XOPEN_PATH_MAX
+namespace fs = std::filesystem;
+
+#ifndef _WIN32
+static const char preferred_separator = fs::path::preferred_separator;
 #else
-# define IGN_PATH_MAX _POSIX_PATH_MAX
+static const char preferred_separator = '\\';
```
Comment (chapulina) [inline src/Filesystem.cc:40]: Do we need these static separators? What's the difference between this and the `::separator` function?

Also

```suggestion
static const char preferredSeparator = '\\';
```

**Review by chapulina — COMMENTED** [review]
Great to see all that custom code going away! I just have minor comments below

File: src/DirIter.cc (hunk 4 above)
Comment (mjcarroll) [reply src/DirIter.cc]: 50455b6

File: src/Filesystem.cc (hunk 6 above)
Comment (mjcarroll) [reply src/Filesystem.cc]: 7b0ddfc

File: src/Filesystem.cc (hunk 7 above)
Comment (mjcarroll) [reply src/Filesystem.cc]: Not sure, I think it was something windows related, I'll try to drop it and see what happens.

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by mjcarroll** [comment]
@chapulina down to three really suspicious failures here:

```
UNIT_KeyEvent_TEST.test_ran
UNIT_Pbr_TEST.test_ran
UNIT_Profiler_Remotery_TEST.test_ran
```

KeyEvent and `Profiler_Remotery` both segault and neither make use of filesystem, as far as I can tell.

**Comment by chapulina** [comment]
> down to three really suspicious failures here:

Suspicious indeed. They all seem to segfault even before the test starts, so maybe it's something within GTest? Could the `CXX_FILESYSTEM_LIBRARIES` have affected it? I can't tell what these tests have in common that's specific to them. They all use `TEST` and don't have a `main`, but other tests do too and they're passing.

**Comment by scpeters** [comment]
> > down to three really suspicious failures here:
> 
> Suspicious indeed. They all seem to segfault even before the test starts, so maybe it's something within GTest? Could the `CXX_FILESYSTEM_LIBRARIES` have affected it? I can't tell what these tests have in common that's specific to them. They all use `TEST` and don't have a `main`, but other tests do too and they're passing.

weird that the tests only fail in jenkins, not in Github actions

**Comment by scpeters** [comment]
> > > down to three really suspicious failures here:
> > 
> > 
> > Suspicious indeed. They all seem to segfault even before the test starts, so maybe it's something within GTest? Could the `CXX_FILESYSTEM_LIBRARIES` have affected it? I can't tell what these tests have in common that's specific to them. They all use `TEST` and don't have a `main`, but other tests do too and they're passing.
> 
> weird that the tests only fail in jenkins, not in Github actions

those failures occurred on the r2d2 machine, which I have taken offline for testing. I see the following when I try to load one of the failing tests in gdb on r2d2:

~~~
Reading symbols from bin/UNIT_Pbr_TEST...
(gdb) r
Starting program: /var/lib/jenkins/workspace/ignition_common-ci-pr_any-ubuntu_auto-amd64/build/bin/UNIT_Pbr_TEST 
warning: Error disabling address space randomization: Operation not permitted
warning: Could not trace the inferior process.
warning: ptrace: Operation not permitted
During startup program exited with code 127.
~~~

**Comment by scpeters** [comment]
I downloaded the `Dockerfile` and `build.sh` script from the jenkins job and with a few modifications was able to get it running on my local machine. I collected the following backtrace from `UNIT_Pbr_TEST`:

~~~
Reading symbols from bin/UNIT_Pbr_TEST...
(gdb) r
Starting program: /home/jenkins/workspace/ignition_common-ci-pr_any-ubuntu_auto-amd64/build/bin/UNIT_Pbr_TEST 
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
std::filesystem::__cxx11::path::~path (this=0x0, __in_chrg=<optimized out>)
   at /usr/include/c++/8/bits/fs_path.h:209
209      ~path() = default;
(gdb) thread apply all bt

Thread 1 (Thread 0x7fb0423e1c40 (LWP 4110)):
#0 std::filesystem::__cxx11::path::~path (this=0x0, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/fs_path.h:209
#1 0x00007fb0438d6434 in std::filesystem::__cxx11::path::_Cmpt::~_Cmpt (this=0x0, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/fs_path.h:644
#2 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt> (__pointer=0x0) at /usr/include/c++/8/bits/stl_construct.h:98
#3 std::_Destroy_aux<false>::__destroy<std::filesystem::__cxx11::path::_Cmpt*> (__last=<optimized out>, __first=0x0) at /usr/include/c++/8/bits/stl_construct.h:108
#4 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/8/bits/stl_construct.h:137
#5 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt> (__last=0x2, __first=<optimized out>) at /usr/include/c++/8/bits/stl_construct.h:206
#6 std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::~vector (this=0x55e9e44c34b0, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:567
#7 std::filesystem::__cxx11::path::~path (this=0x55e9e44c3490, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/fs_path.h:209
#8 std::filesystem::__cxx11::path::_Cmpt::~_Cmpt (this=0x55e9e44c3490, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/fs_path.h:644
#9 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt> (__pointer=0x55e9e44c3490) at /usr/include/c++/8/bits/stl_construct.h:98
#10 std::_Destroy_aux<false>::__destroy<std::filesystem::__cxx11::path::_Cmpt*> (__last=<optimized out>, __first=0x55e9e44c3490) at /usr/include/c++/8/bits/stl_construct.h:108
#11 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/8/bits/stl_construct.h:137
#12 std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt> (__last=0x0, __first=0x55e9e44c3490) at /usr/include/c++/8/bits/stl_construct.h:206
--Type <RET> for more, q to quit, c to continue without paging--c
#13 std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::~vector (this=<synthetic pointer>, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:567
#14 std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::_M_move_assign (__x=..., this=0x7ffe85f32920) at /usr/include/c++/8/bits/stl_vector.h:1679
#15 std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::operator= (__x=..., this=0x7ffe85f32920) at /usr/include/c++/8/bits/stl_vector.h:601
#16 std::filesystem::__cxx11::path::operator= (__p=..., this=0x7ffe85f32900) at /usr/include/c++/8/bits/fs_path.h:797
#17 std::filesystem::__cxx11::path::operator= (__p=..., this=0x7ffe85f32900) at /usr/include/c++/8/bits/fs_path.h:791
#18 ignition::common::joinPaths (_path1="/home/jenkins", _path2=".ignition") at /home/jenkins/workspace/ignition_common-ci-pr_any-ubuntu_auto-amd64/ign-common/src/Filesystem.cc:143
#19 0x00007fb0438e3cf9 in ignition::common::SystemPaths::SystemPaths (this=0x55e9e44c3460) at /usr/include/c++/8/bits/basic_string.h:252
#20 0x00007fb0438cccc5 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /home/jenkins/workspace/ignition_common-ci-pr_any-ubuntu_auto-amd64/ign-common/src/Util.cc:564
#21 _GLOBAL__sub_I_Util.cc(void) () at /home/jenkins/workspace/ignition_common-ci-pr_any-ubuntu_auto-amd64/ign-common/src/Util.cc:564
#22 0x00007fb043e2eb8a in ?? () from /lib64/ld-linux-x86-64.so.2
#23 0x00007fb043e2ec91 in ?? () from /lib64/ld-linux-x86-64.so.2
#24 0x00007fb043e1e13a in ?? () from /lib64/ld-linux-x86-64.so.2
#25 0x0000000000000001 in ?? ()
#26 0x00007ffe85f34d24 in ?? ()
#27 0x0000000000000000 in ?? ()
(gdb)
~~~

File: src/Util.cc [hunk 8]
```diff
@@ -55,8 +57,19 @@
...
+///
+/// This uses the NeverDestroyed pattern to prevent static initialization and
+/// destruction order fiasco issues.
+ignition::common::SystemPaths* GetSystemPaths()
+{
+  static const
+    ignition::utils::NeverDestroyed<ignition::common::SystemPaths*> paths{
+      new ignition::common::SystemPaths()
+    };
+  return paths.Access();
```
Comment (azeey) [inline src/Util.cc:71]: I was under the impression you can just do 
```c++
  static const ignition::utils::NeverDestroyed<ignition::common::SystemPaths> paths;
  return &paths.Access();
```

without the `new`.

Comment (mjcarroll) [reply src/Util.cc:71]: Ah, good point, I think this may have been a workaround for something `const`.  Will fix.

**Comment by mjcarroll** [comment]
Waiting on https://github.com/osrf/homebrew-simulation/pull/1796

**Comment by scpeters** [comment]
> Waiting on [osrf/homebrew-simulation#1796](https://github.com/osrf/homebrew-simulation/pull/1796)

I just merged it and restarted the homebrew build

File: src/SystemPaths.cc [hunk 9]
```diff
@@ -403,6 +390,8 @@ std::string SystemPaths::FindFile(const std::string &_filename,
   // Try appending to local paths
   else
   {
+    ignerr << "Here: " << cwd() << " " << filename << std::endl;
```
Comment (scpeters) [inline src/SystemPaths.cc:393]: remove this debugging message

File: src/SystemPaths.cc [hunk 10]
```diff
@@ -465,9 +454,12 @@ std::string SystemPaths::FindFile(const std::string &_filename,
 std::string SystemPaths::LocateLocalFile(const std::string &_filename,
     const std::vector<std::string> &_paths)
 {
+  std::cerr << "LocateLocalFile: " << _filename << "\n";
```
Comment (scpeters) [inline src/SystemPaths.cc:457]: remove this debugging message

File: src/SystemPaths.cc [hunk 11]
```diff
@@ -465,9 +454,12 @@ std::string SystemPaths::FindFile(const std::string &_filename,
...
+
   std::string foundPath = "";
   for (auto const &path : _paths)
   {
+    std::cout << "\tPath: " << path << "\n";
```
Comment (scpeters) [inline src/SystemPaths.cc:462]: remove this debugging message

File: src/SystemPaths.cc [hunk 12]
```diff
@@ -531,6 +523,8 @@ void SystemPaths::AddFindFileURICallback(
 /////////////////////////////////////////////////
 std::list<std::string> SystemPaths::PathsFromEnv(const std::string &_env)
 {
+  std::cerr << "PathsFromEnv" << std::endl;
```
Comment (scpeters) [inline src/SystemPaths.cc:526]: remove this debugging message

**Review by scpeters — COMMENTED** [review]
a few debug messages can be removed

File: test/performance/logging.cc [hunk 13]
```diff
@@ -196,7 +196,7 @@ TEST_P(LoggingTest, RunThreads)
 }
 
 INSTANTIATE_TEST_SUITE_P(LoggingTest, LoggingTest,
-                         ::testing::Values(1, 2, 4, 8, 16, 32));
+                         ::testing::Values(1, 2, 4, 8, 16));
```
Comment (scpeters) [inline test/performance/logging.cc:199]: these changes will conflict with #302

Comment (mjcarroll) [reply test/performance/logging.cc:199]: Let's get the forward port done first, and then I will sort it out.

File: src/SystemPaths.cc (hunk 9 above)
Comment (scpeters) [reply src/SystemPaths.cc:393]: this one too?

File: test/performance/logging.cc (hunk 13 above)
Comment (scpeters) [reply test/performance/logging.cc:199]: this is close; I'll just resolve the conflicts when merging forward

File: src/SystemPaths.cc (hunk 9 above)
Comment (scpeters) [reply src/SystemPaths.cc]: removed in https://github.com/ignitionrobotics/ign-common/pull/238/commits/6ab5b607bd7d36acea1fec722965a13bb1d507dc

File: src/Filesystem.cc [hunk 14]
```diff
@@ -36,466 +30,288 @@
...
+  else
+    is_url = true;
 
-  // This is a Windows path, convert all '/' into backslashes
-  std::string result = std::regex_replace(_path, std::regex(R"(/)"), "\\");
-  std::string drive_letters;
+  if (_path2.find("://") == std::string::npos)
+    p2 = p2.lexically_normal();
+  else
+    is_url = true;
```
Comment (scpeters) [inline src/Filesystem.cc:150]: shouldn't it be an error if `_path2` is a URL? I guess unless `_path1` is empty. Maybe our existing tests don't address that, but it seems like a problem

**Review by scpeters — COMMENTED** [review]
two comments about Filesystem.cc

File: test/performance/logging.cc (hunk 13 above)
Comment (scpeters) [reply test/performance/logging.cc:199]: forward port is done, feel free to resolve conflicts

File: src/Filesystem.cc (hunk 14 above)
Comment (mjcarroll) [reply src/Filesystem.cc:150]: You are correct that it's strange.  It _likely_ should happen, but there is nothing stopping users from doing it.

I think I'd like to address this in a follow-up PR as it's out of the scope of our current test suite.

File: src/Filesystem.cc [hunk 15]
```diff
@@ -36,466 +30,288 @@
...
+  return fsWarn("createDirectory", ec);
+}
 
-  return ignition::common::removeDirectoryOrFile(_path, _warningOp);
+/////////////////////////////////////////////////
+bool ignition::common::createDirectories(const std::string &_path)
+{
+  std::error_code ec;
+  // Disregard return here because it may return false if the
+  // directory is not actually created (already exists)
```
[the remark this answers is not in the document]
Comment (mjcarroll) [reply src/Filesystem.cc:88]: I wasn't actually doing anything with the `bool` return.  I think I have made it more clear in [66f716c](https://github.com/ignitionrobotics/ign-common/pull/238/commits/66f716ca291a170b261a49cdb9cad4d90cba2859)

File: src/Filesystem.cc (hunk 14 above)
Comment (scpeters) [reply src/Filesystem.cc:151]: can you add a todo comment before merging this?

Comment (mjcarroll) [reply src/Filesystem.cc:151]: Done.

File: src/Filesystem.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (mjcarroll) [reply src/Filesystem.cc:87]: Reworded to indicate which return value I'm talking about.

**Review by scpeters — APPROVED** [review]
